'use strict';
(() => {
  const $=id=>document.getElementById(id), KEY='luke.fashion.pipeline.v1';
  let mode='tryon',jobs=[],controller=null,previews=[];
  const status=text=>{$('status').textContent=text;};
  function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');jobs=Array.isArray(x.jobs)?x.jobs.slice(0,100):[];$('webhook').value=typeof x.webhook==='string'?x.webhook:'';}catch{jobs=[];}draw();}
  function save(){try{localStorage.setItem(KEY,JSON.stringify({webhook:$('webhook').value.trim(),jobs:jobs.slice(0,100)}));}catch{status('브라우저 저장공간을 사용할 수 없어요. 기록을 내보내 주세요.');}}
  function setMode(next){mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('on',b.dataset.mode===mode));const batch=mode==='batch';$('person-label').firstChild.textContent=batch?'기준 모델 사진 (선택)':'사람 또는 확정 모델 사진';$('person').required=!batch;$('garments').multiple=batch;$('garment-help').textContent=batch?'최대 10장':'1장';status(batch?'대량 룩북 모드: 의류 파일을 최대 10장 선택하세요.':'방문자 피팅 모드: 사람 사진과 의류 사진을 각각 선택하세요.');renderPreviews();}
  document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
  function uid(){return crypto.randomUUID?crypto.randomUUID():'job-'+Date.now()+'-'+Math.random().toString(36).slice(2);}
  async function imageData(file){if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1048576)throw new Error((file?.name||'이미지')+': JPG·PNG·WebP 8MB 이하만 가능해요.');const raw=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});const im=new Image();await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=()=>reject(new Error(file.name+': 이미지를 읽지 못했어요.'));im.src=raw;});const scale=Math.min(1,1600/Math.max(im.width,im.height));if(scale===1&&file.size<3*1048576)return raw;const c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*scale));c.height=Math.max(1,Math.round(im.height*scale));c.getContext('2d').drawImage(im,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.9);}
  function renderPreviews(){previews.forEach(URL.revokeObjectURL);previews=[];$('previews').replaceChildren();const files=[...($('person').files||[]),...($('garments').files||[])].slice(0,11);for(const f of files){const u=URL.createObjectURL(f);previews.push(u);const fig=document.createElement('figure'),im=document.createElement('img'),cap=document.createElement('figcaption');im.src=u;im.alt='선택 이미지 미리보기';cap.textContent=f.name;fig.append(im,cap);$('previews').append(fig);}}
  $('person').onchange=renderPreviews;$('garments').onchange=renderPreviews;
  function chooseProvider(){const chosen=$('provider').value;if(chosen!=='auto')return chosen;return mode==='batch'?'claid':'fashn';}
  function draw(){const q=$('queue');q.replaceChildren();if(!jobs.length){const p=document.createElement('p');p.textContent='아직 실행한 작업이 없어요.';p.className='security';q.append(p);return;}for(const j of jobs){const card=document.createElement('article');card.className='job';const state=document.createElement('div');state.className='state '+j.status;state.textContent=({queued:'대기',running:'처리 중',completed:'완료',failed:'실패',cancelled:'중지'})[j.status]||j.status;const info=document.createElement('div'),h=document.createElement('strong'),p=document.createElement('p');h.textContent=j.project+' · '+j.garment;p.textContent=j.provider.toUpperCase()+' · '+new Date(j.createdAt).toLocaleString('ko-KR')+(j.message?' · '+j.message:'');info.append(h,p);if(j.output_url){const a=document.createElement('a');a.href=j.output_url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='결과 보기 ↗';info.append(a);}const id=document.createElement('small');id.textContent=j.database_id?'DB '+j.database_id:j.id.slice(0,12);card.append(state,info,id);q.append(card);}}
  function update(id,patch){const j=jobs.find(x=>x.id===id);if(j)Object.assign(j,patch);save();draw();}
  $('save-webhook').onclick=()=>{const url=$('webhook').value.trim();if(!/^https:\/\//.test(url)){status('HTTPS Make 웹훅 주소를 입력해 주세요.');return;}save();status('연결 주소를 이 브라우저에 저장했어요.');};
  $('test-webhook').onclick=async()=>{const url=$('webhook').value.trim();if(!/^https:\/\//.test(url)){status('HTTPS Make 웹훅 주소를 먼저 입력해 주세요.');return;}controller=new AbortController();$('test-webhook').disabled=true;try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event:'fashion.connection.test',source:'lukemodel.com',sent_at:new Date().toISOString()}),signal:controller.signal,credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw new Error('HTTP '+r.status);status('Make 웹훅이 응답했어요. 연결됐습니다.');save();}catch(e){status('연결 확인 실패: '+(e.name==='AbortError'?'중지됨':e.message));}finally{$('test-webhook').disabled=false;controller=null;}};
  $('pipeline-form').onsubmit=async e=>{e.preventDefault();const webhook=$('webhook').value.trim(),garments=[...$('garments').files||[]].slice(0,mode==='batch'?10:1),person=$('person').files[0]||null;if(!/^https:\/\//.test(webhook)){status('Make Custom Webhook URL을 먼저 연결해 주세요.');return;}if(!garments.length||(!person&&mode==='tryon')){status('필요한 사람·의류 사진을 선택해 주세요.');return;}if(!$('consent').checked){status('사진 처리·전송 동의가 필요해요.');return;}controller=new AbortController();document.querySelectorAll('#pipeline-form input,#pipeline-form select,#pipeline-form textarea,#pipeline-form button').forEach(n=>n.disabled=true);$('cancel').disabled=false;let personData=null;try{if(person)personData=await imageData(person);for(let i=0;i<garments.length;i++){const garment=garments[i],id=uid(),provider=chooseProvider(),job={id,status:'running',project:$('project').value.trim(),garment:garment.name,provider,createdAt:new Date().toISOString()};jobs.unshift(job);save();draw();status((i+1)+'/'+garments.length+' · '+garment.name+' 전송 중…');try{const garmentData=await imageData(garment),payload={event:mode==='batch'?'fashion.batch.requested':'fashion.tryon.requested',job_id:id,provider,project:job.project,category:$('category').value,person:personData?{name:person.name,data_url:personData}:null,garment:{name:garment.name,data_url:garmentData},prompt:$('prompt').value.trim(),source:'lukemodel.com',callback_expected:{status:'completed',output_url:'https://...',database_id:'record-id'}};const r=await fetch(webhook,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal,credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw new Error('HTTP '+r.status);let data={};try{data=await r.json();}catch{}update(id,{status:data.status==='queued'?'queued':'completed',output_url:typeof data.output_url==='string'?data.output_url:'',database_id:String(data.database_id||''),message:data.message||'Make 응답 완료'});}catch(err){update(id,{status:err.name==='AbortError'?'cancelled':'failed',message:err.name==='AbortError'?'사용자가 중지함':err.message});if(err.name==='AbortError')break;}}status('파이프라인 실행을 마쳤어요. 작업 카드와 Make 실행 기록을 확인하세요.');}catch(err){status('실행 실패: '+err.message);}finally{document.querySelectorAll('#pipeline-form input,#pipeline-form select,#pipeline-form textarea,#pipeline-form button').forEach(n=>n.disabled=false);$('cancel').disabled=true;controller=null;}};
  $('cancel').onclick=()=>controller?.abort();
  $('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({exported_at:new Date().toISOString(),jobs},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='luke-fashion-jobs.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  $('clear-completed').onclick=()=>{jobs=jobs.filter(j=>!['completed','failed','cancelled'].includes(j.status));save();draw();status('완료·실패·중지 기록을 화면에서 정리했어요.');};
  window.addEventListener('pagehide',()=>{controller?.abort();previews.forEach(URL.revokeObjectURL);});
  load();setMode('tryon');
})();
